name: Exemplo Input
run-name: Exemplo workflow para input, executado por ${{ github.actor}}
on:
    workflow_dispatch:
jobs:
    gerando_output:
        runs-on: ubuntu-latest
        steps:
            - name: Gerando output com shell
              id: exemplo-output
              run: |
                ACTION_RANDOM=$(( $RANDOM ))
                echo action_random=$ACTION_RANDOM" >> $GITHUB_OUTPUT

            - name: Exibindo o output da action exemplo output
              run: echo "${{ steps.exemplo-output.outputs.action_random }}"
